### PR TITLE
Qualifier Test

### PR DESCRIPTION
**Pull request by talha8045**

### CODE REVIEW

**Comment by flozender** [comment]
Great work! Just a few changes from my side:

- [ ] Let users end test before timer runs out with a confirmation (Edit `ValidTill` to make it equal to `StartTime`)
- [ ] Remove MCQ Name from XLSX sheet
- [ ] Total Score = Score/Total Questions
- [ ] Each Section = Correct - Wrong - Unanswered 
- [ ] Contest ID and Contest Name on Results page
- [ ] Go Home and print button on results page
- [ ] Change navbar to Qualifier Test
- [ ] Add images to MCQs
- [ ] Add answers table to results

**Comment by talha8045** [comment]
I've updated the PR.

**Comment by flozender** [comment]
- [ ] Show section only when questions exist 
- [ ] color number of correct and wrong answers (when more than 0)

**Comment by talha8045** [comment]
I have Impleted both the changes.

**Comment by flozender** [comment]
Thanks! LGTM.

**Pull request merged**
